version: "3"
services:
  psql:
    image: psql
    ports:
      - "5432:${PORT}"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: